# Generated by Django 3.2.4 on 2021-06-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20210611_1856'),
        ('cadastro', '0002_conta'),
    ]

    operations = [
    ]
